# Generated by Django 5.1 on 2024-08-31 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='brach',
            new_name='branch',
        ),
    ]
